### ISSUE TITLE
Problems running Alice 2 on Mac OS 13 Ventura

### ISSUE THREAD

**Issue by dabeshouse** [TheAliceProject/alice2#4]
Alice 2 requires Rosetta but is not correctly identified as `Application(Intel)` so attempts to run it fail without requesting Rosetta be installed.

Once Rosetta is installed it displays the splash screen and a dialog requesting access to the Desktop folder. If the user says no it can be granted later from the system preferences, but with or without that access does not get past the splash screen.
It pegs one CPU and has to be forced to quit.

**Comment by MelanieLam** [comment]
Alice 2.6 release resolves this on Mac OS 13 onward.
Also includes compatible Windows/Linux versions.

https://github.com/TheAliceProject/alice2/releases/tag/2.6.0
